default: &default
  adapter: postgresql
  encoding: UTF-8
  pool: 5

development:
  <<: *default
  database: gas_channels_development

test:
  <<: *default
  database: gas_channels_test

production:  
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %> #This is the environment variable created by our Dokku command earlier
  encoding: unicode
  pool: 5